name: JMeter CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Install JMeter
      - name: Install JMeter
        run: |
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.zip -O jmeter.zip
          unzip -o jmeter.zip
          sudo mv apache-jmeter-5.6.3 /usr/share/jmeter
          echo "PATH=$PATH:/usr/share/jmeter/bin" >> $GITHUB_ENV

      # Step 4: Run JMeter Test Plan
      - name: Run JMeter Test Plan
        run: |
          mkdir -p src/test/jmeter/results
          jmeter -n -t src/test/jmeter/maventest1.jmx -l src/test/jmeter/results/test1.jtl

      # Step 5: Upload Test Results as Artifacts
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: ${{ github.workspace }}/src/test/jmeter/results/
